insert into Articlib.AspNetUsers (Id,
                                  Email,
                                  NormalizedEmail,
                                  UserName,
                                  NormalizedUserName,
                                  PasswordHash,
                                  EmailConfirmed,
                                  SecurityStamp,
                                  LockoutEnabled,
                                  AccessFailedCount,
                                  PhoneNumberConfirmed,
                                  TwoFactorEnabled,
                                  ConcurrencyStamp)
values ('99999999-9999-9999-9999-999999999999',
        'test@articlib.com',
        'TEST@ARTICLIB.COM',
        'TestUser',
        'TESTUSER',
        'AQAAAAEAACcQAAAAEBYySyHME7wyhlLcJVcnFOTuNoIr5FpVnlyLKQ4dL0VgiEE3E9ztqUq1aUXhob/i6w==',
        0,
        '',
        false,
        0,
        0,
        0,
        '');
